### ISSUE TITLE
Configure Issues Template for a New Class

### ISSUE THREAD

**Issue by michaelputnam67** [angelewilliams/whats-cooking#8]
### Description
I would like to set up an issues template for adding a new class however that has to be done under settings to which only the owner of the repository has access. 

[Here is a link to the docs for creating an issues template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by angelewilliams** [comment]
Great idea!
